### ISSUE TITLE
Problème avec sabnzbd, impossible à configurer

### ISSUE THREAD

**Issue by Bono2007** [projetssd/ssdv2#63]
sabnzbd.yml : 
```
---
application: 'sabnzbd'
app_port: 8080
description: "SABnzbd est un lecteur de newsgroups"
image: 'lscr.io/linuxserver/sabnzbd:latest'
application_volumes:
  - local_path: "{{ lookup('env','APP_SETTINGS') }}/{{application}}/config"
    container_path: "/config"
  - local_path: "{{ lookup('env','APP_SETTINGS') }}/{{application}}/data"
    container_path: "/data"
  - local_path: "{{ lookup('env','HOME') }}"
    container_path: "{{ lookup('env','HOME') }}"
application_env:
  - name: PUID
    value: '{{user.userid}}'
  - name: PGID
    value: '{{user.groupid}}'
  - name: TZ
    value: 'Europe/Paris'
#posttasks:
#  - configure_sabnzbd
#  - restart
```
Fonctionne  mais : Access denied - Hostname verification failed: https://sabnzbd.org/hostname-check
Or j'ai changé sabnzbd.ini : 
```cat sabnzbd.ini | grep whitelist
host_whitelist = sabnzbd-58f7495848-v7cd4,sabnzbd.ndd.fr,sabnzbd,
```

Même message. 

Autre chose, la posttask ne fonctionne pas, le fichier est bien trouvé mais le changement ne se fait pas : 
```---
- name: wait for files to be present
  wait_for:
    path: "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config/sabnzbd.ini"
- name: Add sabnzbd
  lineinfile:
    path: "{{ lookup('env', 'APP_SETTINGS') }}/{{application}}/config/sabnzbd.ini"
    regexp: '^(host_whitelist\s*=.*)'
    line: '\1 sabnzbd'
    state: present
```
